export const destinations = [
  {
    id: 1,
    name: "Santorini, Greece",
    description: "Iconic white-washed buildings overlooking the Aegean Sea",
    image: "/santorini-sunset.png",
    price: 2499,
    duration: "7 days",
    rating: 4.9,
    category: "beach",
  },
  {
    id: 2,
    name: "Kyoto, Japan",
    description: "Ancient temples and serene bamboo forests await",
    image: "/kyoto-japan-temple-bamboo-forest.jpg",
    price: 3199,
    duration: "10 days",
    rating: 4.8,
    category: "cultural",
  },
  {
    id: 3,
    name: "Machu Picchu, Peru",
    description: "Walk among the clouds in this ancient Incan citadel",
    image: "/machu-picchu-ruins.png",
    price: 2899,
    duration: "8 days",
    rating: 4.9,
    category: "adventure",
  },
  {
    id: 4,
    name: "Maldives",
    description: "Crystal clear waters and overwater luxury villas",
    image: "/maldives-overwater-villa-crystal-blue-ocean.jpg",
    price: 4599,
    duration: "6 days",
    rating: 5.0,
    category: "beach",
  },
  {
    id: 5,
    name: "Swiss Alps",
    description: "Majestic peaks and charming alpine villages",
    image: "/swiss-alps-mountains-village-snow.jpg",
    price: 3499,
    duration: "9 days",
    rating: 4.7,
    category: "adventure",
  },
  {
    id: 6,
    name: "Marrakech, Morocco",
    description: "Vibrant souks and stunning Moorish architecture",
    image: "/marrakech-morocco-colorful-market-architecture.jpg",
    price: 1899,
    duration: "5 days",
    rating: 4.6,
    category: "cultural",
  },
]

export const packages = [
  {
    id: 1,
    name: "European Dream",
    description: "Paris, Rome, and Barcelona in one unforgettable journey",
    image: "/europe-paris-eiffel-tower-rome-colosseum.jpg",
    price: 5999,
    duration: "14 days",
    rating: 4.9,
    highlights: ["Eiffel Tower", "Colosseum", "Sagrada Familia", "Gondola Ride"],
    featured: true,
  },
  {
    id: 2,
    name: "Asian Explorer",
    description: "Tokyo, Bangkok, and Bali - the best of Asia",
    image: "/asia-tokyo-temple-bangkok-bali.jpg",
    price: 4799,
    duration: "12 days",
    rating: 4.8,
    highlights: ["Mount Fuji", "Grand Palace", "Ubud Rice Terraces", "Street Food Tours"],
    featured: true,
  },
  {
    id: 3,
    name: "African Safari",
    description: "Witness the great migration in the Serengeti",
    image: "/african-safari-serengeti-lions-elephants-sunset.jpg",
    price: 6499,
    duration: "10 days",
    rating: 5.0,
    highlights: ["Big Five Safari", "Masai Village", "Hot Air Balloon", "Luxury Lodges"],
    featured: true,
  },
  {
    id: 4,
    name: "Caribbean Escape",
    description: "Island hopping through paradise",
    image: "/caribbean-islands-beach-turquoise-water-palm-trees.jpg",
    price: 3299,
    duration: "7 days",
    rating: 4.7,
    highlights: ["Private Beach", "Snorkeling", "Rum Tasting", "Sunset Cruise"],
    featured: false,
  },
]

export const testimonials = [
  {
    id: 1,
    name: "Sarah Mitchell",
    location: "New York, USA",
    text: "Wanderly made our honeymoon absolutely magical. Every detail was perfect, from the boutique hotels to the private tours.",
    avatar: "/professional-woman-smiling-headshot.png",
    trip: "Santorini Escape",
    rating: 5,
  },
  {
    id: 2,
    name: "James Chen",
    location: "London, UK",
    text: "The African Safari exceeded all expectations. The guides were incredibly knowledgeable and the accommodations were world-class.",
    avatar: "/man-smiling-professional-headshot-asian.jpg",
    trip: "African Safari",
    rating: 5,
  },
  {
    id: 3,
    name: "Maria Garcia",
    location: "Madrid, Spain",
    text: "I've traveled with many agencies, but Wanderly's attention to detail and personalized service is unmatched.",
    avatar: "/woman-smiling-professional-headshot-brunette.jpg",
    trip: "Asian Explorer",
    rating: 5,
  },
]

export const teamMembers = [
  {
    id: 1,
    name: "Alexandra Rivers",
    role: "Founder & CEO",
    bio: "With 15 years in luxury travel, Alex founded Wanderly to share her passion for transformative journeys.",
    image: "/professional-woman-ceo-headshot-elegant.jpg",
  },
  {
    id: 2,
    name: "Marcus Thompson",
    role: "Head of Experiences",
    bio: "Marcus has explored over 80 countries, curating unique experiences that go beyond typical tourism.",
    image: "/professional-man-travel-expert-headshot.jpg",
  },
  {
    id: 3,
    name: "Yuki Tanaka",
    role: "Asia Specialist",
    bio: "Born in Tokyo, Yuki brings authentic insider knowledge to all our Asian destinations.",
    image: "/professional-woman-asian-travel-specialist-headsho.jpg",
  },
]
